formatter: "markdown" # this is required

version: ""

header-from: "docs/pattern-doc-header.md"
footer-from: "docs/pattern-doc-footer.md"

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0

content: |-
  {{ .Header }}
  {{ include "docs/pattern-description.md" }}


  ## Reference Example

  ```hcl
  {{ include "examples/example.tf" }}
  ```


  {{ .Inputs }}


  {{ .Outputs }}


  {{ .Providers }}

  {{ include "docs/pattern-doc-config-layers.md" }}

  {{ .Footer }}

output:
  file: "README.md"
  mode: replace
  template: |-

    <!-- BEGINNING OF PRE-COMMIT-OPENTOFU DOCS HOOK -->

    {{ .Content }}

    <!-- END OF PRE-COMMIT-OPENTOFU DOCS HOOK -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
